# fly.toml file for Landbuyer

app = "landbuyer"
primary_region = "ams"
kill_signal = "SIGTERM"
swap_size_mb = 512

# Optionnel : tu peux supprimer complètement cette section si tu ne fais pas de release spécifique
#[deploy]
# release_command = "/app/bin/landbuyer eval \"IO.puts('Release ran successfully')\""

[env]
  PHX_HOST = "landbuyer.fly.dev"
  PORT     = "8080"

[http_service]
  internal_port        = 8080
  force_https          = true
  auto_stop_machines   = true
  auto_start_machines  = true
  min_machines_running = 1
  processes            = ["app"]

[http_service.concurrency]
  type       = "connections"
  hard_limit = 1000
  soft_limit = 1000

[[vm]]
  cpu_kind  = "shared"
  cpus      = 1
  memory_mb = 256
