# fly.toml app configuration file generated for landbuyer on 2023-12-18T18:42:58+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app            = "landbuyer"
primary_region = "ams"
kill_signal    = "SIGTERM"
swap_size_mb   = 512

#[deploy]
#  release_command = "/app/bin/migrate"

[env]
  PHX_HOST = "landbuyer.fly.dev"
  PORT     = "8080"

[http_service]
  internal_port        = 8080
  force_https          = true
  auto_stop_machines   = true
  auto_start_machines  = true
  min_machines_running = 1
  processes            = ["app"]

[http_service.concurrency]
  type       = "connections"
  hard_limit = 1000
  soft_limit = 1000

[[vm]]
  cpu_kind  = "shared"
  cpus      = 1
  memory_mb = 256
  
[processes]
  app = "/app/bin/landbuyer start"
